name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v1

    - shell: bash
      run: bun add -g turbo

    - shell: bash
      run: bun install

    - name: Set up Next.js Cache for website
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/apps/website/.next/cache
        key: ${{ runner.os }}-nextjs-cache-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('apps/website/**/*.tsx', 'apps/website/**/*.ts') }}
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}
