services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  cron:
    image: alpine/curl
    command: >
      sh -c "
        echo '0 0 * * * curl -X POST http://web:3000/api/cron' > /etc/crontabs/root && \
        crond -f -l 2
      "
    depends_on:
      - web
