services:
  web:
    image: ghcr.io/coeeter/aniways:${GITHUB_SHA:-latest}
    ports:
      - "3000:3000"
    env_file: /run/secrets/env
    environment:
      - NODE_ENV=production
      - CRON_KEY=${CRON_KEY}
      - MAL_CLIENT_ID=${MAL_CLIENT_ID}
      - MAL_CLIENT_SECRET=${MAL_CLIENT_SECRET}
      - MAL_SECRET_KEY=${MAL_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}

  cron:
    image: alpine/curl
    command: >
      sh -c "
        echo '0 0 * * * curl -H \"X-Cron-Key: $$CRON_KEY\" -X POST http://web:3000/api/cron' > /etc/crontabs/root && \
        crond -f -l 2
      "
    depends_on:
      - web
    environment:
      - CRON_KEY=${CRON_KEY}

secrets:
  env:
    external: true
