services:
  web:
    image: ghcr.io/coeeter/aniways:${GITHUB_SHA:-latest}
    ports:
      - "3000:3000"
    secrets:
      - env
    environment:
      - NODE_ENV=production
      - CRON_KEY=${CRON_KEY}

  cron:
    image: alpine/curl
    command: >
      sh -c "
        echo '0 0 * * * curl -H \"X-Cron-Key: $$CRON_KEY\" -X POST http://web:3000/api/cron' > /etc/crontabs/root && \
        crond -f -l 2
      "
    depends_on:
      - web
    environment:
      - CRON_KEY=${CRON_KEY}

secrets:
  env:
    external: true
