import { Jikan4 } from 'node-myanimelist';
export default function getAnimeDetails(name: string, episode?: number): Promise<{
    episodes: {
        current: boolean;
        mal_id?: number | undefined;
        url?: string | undefined;
        title?: string | undefined;
        title_japanese?: string | undefined;
        title_romanji?: string | undefined;
        duration?: number | undefined;
        aired?: string | undefined;
        filler?: boolean | undefined;
        recap?: boolean | undefined;
        forum_url?: string | undefined;
    }[];
    mal_id?: number | undefined;
    url?: string | undefined;
    images: Jikan4.Types.AnimeImages;
    trailer: Jikan4.Types.TrailerBase;
    title?: string | undefined;
    title_english?: string | undefined;
    title_japanese?: string | undefined;
    title_synonyms: string[];
    type?: string | undefined;
    source?: string | undefined;
    status?: string | undefined;
    airing?: boolean | undefined;
    aired: Jikan4.Types.Daterange;
    duration?: string | undefined;
    rating?: string | undefined;
    score: number;
    scored_by?: number | undefined;
    rank?: number | undefined;
    popularity?: number | undefined;
    members?: number | undefined;
    favorites?: number | undefined;
    synopsis?: string | undefined;
    background?: string | undefined;
    season?: string | undefined;
    year?: number | undefined;
    broadcast: Jikan4.Types.Broadcast;
    producers: Jikan4.Types.MalUrl[];
    licensors: Jikan4.Types.MalUrl[];
    studios: Jikan4.Types.MalUrl[];
    genres: Jikan4.Types.MalUrl[];
    explicit_genres: Jikan4.Types.MalUrl[];
    themes: Jikan4.Types.MalUrl[];
    demographics: Jikan4.Types.MalUrl[];
}>;
//# sourceMappingURL=index.d.ts.map