ktor:
  development: true
  application:
    modules:
      - xyz.aniways.ApplicationKt.module
  deployment:
    port: 8080

db:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5432/aniways"
  username: "$DATABASE_USER:postgres"
  password: "$DATABASE_PASSWORD:password"