ktor:
  url: "$API_URL:http://localhost:8080"
  frontend: "$FRONTEND_URL:http://localhost:3000"
  development: "$DEVELOPMENT:false"
  application:
    modules:
      - xyz.aniways.ApplicationKt.module
  deployment:
    port: 8080

db:
  url: "$DATABASE_URL:jdbc:postgresql://localhost:5432/aniways"
  username: "$DATABASE_USER:postgres"
  password: "$DATABASE_PASSWORD:password"

mal:
  clientId: "$MAL_CLIENT_ID"
  clientSecret: "$MAL_CLIENT_SECRET"

redis:
  host: "$REDIS_HOST:localhost"
  port: "$REDIS_PORT:6379"