name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: aniways-aws-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # ENV Variables for the project
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
      MAL_CLIENT_SECRET: ${{ secrets.MAL_CLIENT_SECRET }}
      MAL_SECRET_KEY: ${{ secrets.MAL_SECRET_KEY }}
      # For AWS
      AWS_CERT_ARN: ${{ secrets.AWS_CERT_ARN }}
      # For TurboRepo
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install serverless
        run: bun add -g serverless@3.34.0

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to AWS
        run: bun run deploy:prod
