name: Deploy

on:
  push:
    branches:
      - "main"
      - "vps"

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/coeeter/aniways:latest
            ghcr.io/coeeter/aniways:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - uses: actions/checkout@v4

      - name: Create Cron Key
        run: |
          CRON_KEY=$(openssl rand -hex 32)
          echo "::add-mask::$CRON_KEY"
          echo "CRON_KEY=$CRON_KEY" >> $GITHUB_ENV

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: aniways
          host: ${{ secrets.SSH_HOST }}
          user: deploy
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
