name: Deploy

on:
  push:
    branches:
      - 'main'
      - 'new-beginnings'

permissions:
  packages: write
  contents: read

jobs:
  build-and-push-aniways-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/coeeter/aniways-api:latest
            ghcr.io/coeeter/aniways-api:${{ github.sha }}

  build-and-push-aniways-streaming-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./streaming
          push: true
          tags: |
            ghcr.io/coeeter/aniways-streaming:latest
            ghcr.io/coeeter/aniways-streaming:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-aniways-api-image
      - build-and-push-aniways-streaming-image
    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GITHUB_SHA=${{ github.sha }}" >> .env
          echo "LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}" >> .env
          echo "${{ secrets.ENV }}" >> .env

      - name: Docker Stack Deploy
        uses: kitconcept/docker-stack-deploy@v1.0.1
        env:
          ENV_FILE: .env
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: deploy
          remote_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          stack_file: docker-compose.yaml
          stack_name: aniways
